[package]
name = "horrorshow"
description = "a templating library written in rust macros"
version = "0.2.0"
authors = ["Steven Allen <steven@stebalien.com>"]

[dev-dependencies]
maud = "*"
maud_macros = "*"
